import {VERSION,PROFILES,TRAITS,SOURCES,profileFor,compareAssessments,scoreObservation,validateObservation,morphKeys} from './engine.js';
import {CSV_HEADER,parseCSV,validateTransactions,estimatePrice} from './market.js';
import {summarizeFeedback} from './feedback.js';
import {createWorkerClient} from './transport.js';
const {useState,useEffect}=React;
const uid=()=>crypto.randomUUID();
const date=v=>v?new Date(v).toLocaleString('ko-KR'):'';
const statuses={queued:'PC 분석 대기',claiming:'분석 준비 중',analyzing:'사진 분석 중',waiting:'다른 PC 분석 대기',completed:'분석 완료',error:'분석 실패',blocked:'사용 한도 보호'};
let viewed=new Set();try{viewed=new Set(JSON.parse(localStorage.getItem('crevalue_seen_results')||'[]'));}catch{}
const wasSeen=id=>viewed.has(id);
async function markViewed(id,bridge){if(!id||!bridge)return;await bridge.save('crevalue_feedback',{id:'seen-'+id,type:'exposure',assessmentId:id,createdAt:new Date().toISOString()});viewed.add(id);try{localStorage.setItem('crevalue_seen_results',JSON.stringify([...viewed]));}catch{}}
const css=`.cv{font-size:15px;line-height:1.6}.cv-main{padding:16px;max-width:820px;margin:auto}.cv .card{margin:0 0 14px;padding:18px}.cv h2{font-size:18px;margin:0 0 12px}.cv h3{font-size:16px;margin:12px 0 6px}.cv p{margin:8px 0}.cv .cv-muted{color:var(--text2);font-size:13px}.cv-nav{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:16px}.cv button{min-height:44px;cursor:pointer}.cv label{display:block;font-size:14px;margin-bottom:12px}.cv .input{font-size:16px;width:100%;min-height:44px;margin-top:4px;box-sizing:border-box}.cv .cv-row{display:flex;gap:10px;flex-wrap:wrap}.cv .cv-row>*{flex:1;min-width:130px}.cv-photos{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px}.cv-photo img{width:100%;height:140px;object-fit:contain;background:var(--bg3);border-radius:12px}.cv-photo select{width:100%;min-height:36px}.cv-score{font-size:42px;line-height:1.2;font-weight:800;color:var(--accent2)}.cv-trait{padding:12px 0;border-top:1px solid var(--border)}.cv-bar{height:7px;background:var(--bg3);border-radius:6px;overflow:hidden}.cv-bar span{display:block;background:var(--accent);height:100%}.cv-notice{border-left:3px solid var(--accent);padding:10px 14px;background:var(--accent-soft);border-radius:8px}.cv button:focus-visible,.cv input:focus-visible,.cv select:focus-visible,.cv textarea:focus-visible{outline:3px solid var(--accent2);outline-offset:2px}.cv-table{width:100%;border-collapse:collapse;font-size:13px}.cv-table th,.cv-table td{text-align:left;padding:9px 5px;border-bottom:1px solid var(--border)}.cv-hero{border:1px solid var(--accent-edge)}.cv-hero small{letter-spacing:1px}.cv button:disabled{opacity:.55;cursor:default}.cv-morphs{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0 16px}.cv-morphs button{padding:7px 11px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--text)}.cv-morphs button[aria-pressed=true]{background:var(--accent-soft);border-color:var(--accent);font-weight:700}.cv-empty{padding:28px 10px;text-align:center;color:var(--text2)}@media(max-width:430px){.cv-main{padding:12px}.cv .card{padding:14px}.cv-table{font-size:12px}}`;
function installStyle(){if(document.getElementById('cv-style'))return;const s=document.createElement('style');s.id='cv-style';s.textContent=css;document.head.appendChild(s);}
function exportJson(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function resizePhoto(file){
 if(file.size>25*1024*1024)throw new Error('사진 한 장은 25MB 이하로 선택해 주세요.');
 if(file.type&&!file.type.startsWith('image/'))throw new Error('이미지 파일을 선택해 주세요.');
 const url=URL.createObjectURL(file);
 try{return await new Promise((resolve,reject)=>{const img=new Image();img.onerror=()=>reject(new Error('사진을 읽을 수 없습니다. JPEG·PNG·WebP로 저장해 주세요.'));img.onload=()=>{const scale=Math.min(1,1600/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve({id:uid(),dataUrl:c.toDataURL('image/jpeg',.91),angle:'미지정',fired:'미확인'});};img.src=url;});}finally{URL.revokeObjectURL(url);}
}
function Result({job,bridge}){const r=job?.status==='completed'?job.result:null,[ready,setReady]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;if(r?.source==='ai')void markViewed(job.id,bridge).then(()=>{if(active)setReady(job.id);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[job?.id,r?.source]);if(r?.source==='ai'&&ready!==job.id)return <p role="status">{error||'결과 공개 이력을 저장하고 있습니다…'}</p>;if(!r)return <p role="status">{job?.error||statuses[job?.status]||'결과가 없습니다.'}</p>;return <>
 <div className="cv-row"><div><div className="cv-muted">{r.source==='manual'?'수동 외형 평가':'AI 외형 평가'} · {r.profile.label}</div><div className="cv-score">{r.score===null?'평가 보류':`${r.score}점`}</div></div><div className="cv-muted">관찰 범위 {r.coverage}%<br/>관찰 확신 {r.confidence}% <small>(정확도 아님)</small><br/>{r.model||'수동 평가'}</div></div>
 <p>{r.unavailableReason||r.observation.summary}</p><p className="cv-notice cv-muted">{r.notice}</p>
 <div className="cv-row"><div><h3>관찰된 강점</h3>{r.observation.strengths.map((s,i)=><p key={i}>{s}</p>)}</div><div><h3>부족·확인 불가</h3>{r.observation.limitations.map((s,i)=><p key={i}>{s}</p>)}</div></div>
 {r.traits.map(t=><div className="cv-trait" key={t.id}><strong>{t.label} · {t.score===null?'평가 불가':`${t.score}점`}</strong>{t.score!==null&&<div className="cv-bar"><span style={{width:t.score+'%'}}/></div>}<p>{t.observation}</p><div className="cv-muted">{t.reason}<br/>근거 사진: {t.photoIds.map(id=>'#'+(job.photos?.findIndex(p=>p.id===id)+1||id.slice(0,6))).join(', ')||'없음'}</div></div>)}
 <h3>추가 촬영 제안</h3>{r.observation.suggestions.map((s,i)=><p key={i}>{s}</p>)}<p className="cv-muted">조명: {r.observation.lighting}<br/>꼬리: {r.observation.tail}<br/>기준 {r.version} · {date(r.evaluatedAt||job.createdAt)}</p>
 </>;}
function HistoryRecord({job,bridge,onRetry,report}){
 const [full,setFull]=useState(null),[open,setOpen]=useState(false);
 return <details className="cv-trait" onToggle={async e=>{setOpen(e.currentTarget.open);if(e.currentTarget.open&&!full){try{setFull(await bridge.get('crevalue',job.id));}catch(err){report(err.message);}}}}><summary style={{cursor:'pointer'}}>{job.name} · {job.result&&!wasSeen(job.id)?'결과 펼쳐 보기':job.result?.score!=null?job.result.score+'점':statuses[job.status]}<br/><span className="cv-muted">{date(job.createdAt)} · {job.result?.source==='manual'?'수동':'AI'}</span></summary>{open&&<><div className="cv-photos">{(full?.photos||[]).map((p,i)=><div className="cv-photo" key={p.id}><img src={p.dataUrl} alt={'평가 근거 사진 '+(i+1)}/></div>)}</div><Result bridge={bridge} job={full?{...full,...job,photos:full.photos}:job}/>{['blocked','error'].includes(job.status)&&<button className="btn btn-secondary" onClick={()=>onRetry(job.id)}>다시 분석</button>}</>}</details>;
}
function Manual({profile,photos,onSave}){const [levels,setLevels]=useState({}),[notes,setNotes]=useState({});return <details><summary style={{padding:'12px 0',cursor:'pointer'}}>AI 없이 수동 평가하기</summary><p className="cv-muted">관찰하지 못한 항목은 비워 두십시오. AI 기록과 구분하여 저장합니다.</p>{Object.keys(profile.weights).map(k=><div key={k} className="cv-row"><label>{TRAITS[k][0]}<select className="input" value={levels[k]??''} onChange={e=>setLevels({...levels,[k]:e.target.value})}><option value="">평가 불가</option>{[0,1,2,3,4].map(n=><option value={n} key={n}>{n*25}점 · {['뚜렷한 불균형','불균형 있음','보통','뚜렷하고 균형적','매우 뚜렷하고 균형적'][n]}</option>)}</select></label><label>관찰 근거<input className="input" value={notes[k]||''} onChange={e=>setNotes({...notes,[k]:e.target.value})}/></label></div>)}<button className="btn btn-secondary" disabled={!photos.length} onClick={()=>{
 const o={subject:'gecko',summary:'사용자가 직접 입력한 외형 평가입니다.',tail:'별도 확인 필요',lighting:'사용자 촬영 조건 확인 필요',strengths:[],limitations:[],suggestions:[],traits:Object.keys(profile.weights).map(k=>({id:k,observable:levels[k]!==undefined&&levels[k]!=='',level:levels[k]===undefined||levels[k]===''?null:Number(levels[k]),confidence:0.5,observation:notes[k]||'관찰 내용 미입력',reason:notes[k]||'관찰 근거 미입력',photoIds:levels[k]===undefined||levels[k]===''?[]:photos.map(p=>p.id)}))};
 if(o.traits.some(t=>t.observable&&(!notes[t.id]||!notes[t.id].trim())))return alert('점수를 입력한 항목의 관찰 근거를 적어 주세요.');validateObservation(o,profile,photos.map(p=>p.id));onSave(scoreObservation(o,profile,'manual'));
 }}>수동 평가 저장</button></details>;}

function Market({bridge,animals,report}){
 const [rows,setRows]=useState([]),[draft,setDraft]=useState({id:uid(),morph:'normal',sex:'unknown',status:'unsold',verification:'unverified',rights:'unknown',source:'직접 입력'}),[csv,setCsv]=useState(''),[errors,setErrors]=useState([]),[editing,setEditing]=useState(null);
 const reload=()=>bridge.list('crevalue_market').then(setRows).catch(e=>report(e.message));useEffect(()=>{reload();},[]);
 async function store(list,importing=false){const checked=validateTransactions(list,importing?rows:rows.filter(r=>r.id!==editing));setErrors(checked.errors);if(checked.errors.length)return;await bridge.saveMany('crevalue_market',checked.valid.map(t=>({...t,audit:[...(rows.find(r=>r.id===t.id)?.audit||[]),{at:new Date().toISOString(),action:editing&&!importing?'edit':'create',listedPrice:t.listedPrice,finalPrice:t.finalPrice,verification:t.verification}],priceHistory:[...(rows.find(r=>r.id===t.id)?.priceHistory||[]),{at:new Date().toISOString(),listedPrice:t.listedPrice,finalPrice:t.finalPrice}]})));setEditing(null);setDraft({...draft,id:uid()});await reload();report('거래 데이터를 저장했습니다.');}
 const estimate=estimatePrice({...draft,weight:Number(draft.weight)||null,assessmentScore:draft.assessmentScore==null||draft.assessmentScore===''?null:Number(draft.assessmentScore)},rows);
 return <><div className="card"><h2>참고 분양가</h2><p className="cv-notice">{estimate.range?`${estimate.range[0].toLocaleString()}~${estimate.range[1].toLocaleString()}원`:estimate.reason}</p><p className="cv-muted">유사 검증 거래 {estimate.sampleCount}건 · 최소 {estimate.minSamples}건 · 최근 {estimate.periodDays}일 · 기준일 {estimate.asOf} · 신뢰도 {estimate.confidence}</p>{estimate.range&&<p>{estimate.reason}</p>}</div>
 <div className="card"><h2>{editing?'거래 수정':'거래 직접 입력'}</h2><p className="cv-muted">공개 매물은 등록가입니다. 실제 거래가와 사용 권한을 확인한 자료만 가격 계산에 사용합니다.</p><label>브리딩비서 개체·분양 기록 불러오기<select className="input" value={draft.animalId||''} onChange={e=>{const a=animals.find(g=>g.id===e.target.value);if(a)setDraft({...draft,animalId:a.id,morph:morphKeys(a.morph).join('+'),sex:a.gender||'unknown',weight:a.weight,hatchDate:a.hatchDate,lineage:[a.sireId,a.damId].filter(Boolean).join(' / '),listedPrice:a.salePrice||'',finalPrice:a.finalPrice||'',soldAt:a.soldAt||'',status:a.saleStatus==='sold'?'sold':'unsold',source:'브리딩비서 본인 기록',rights:'owned',verification:'unverified'});}}><option value="">선택하지 않음</option>{animals.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p className="cv-muted">기존 분양 기록을 불러와도 최종 거래가 검증은 직접 확인해야 합니다.</p><div className="cv-row">
 {['animalId','weight','hatchDate','listedPrice','finalPrice','soldAt','source','region','lineage','genetics','assessmentId','assessmentScore','assessmentVersion','transactionTerms','registeredAt'].map(k=><label key={k}>{({animalId:'개체 ID',weight:'체중(g)',hatchDate:'해칭일',listedPrice:'등록 분양가(원)',finalPrice:'최종 거래가(원)',soldAt:'거래일',source:'출처·확인 기록',region:'지역',lineage:'혈통·부모 기록',genetics:'확인된 유전 정보',assessmentId:'평가 기록 ID',assessmentScore:'외형 점수 (선택)',assessmentVersion:'외형 기준 버전',transactionTerms:'거래 조건',registeredAt:'매물 등록일'})[k]}<input className="input" type={['hatchDate','soldAt','registeredAt'].includes(k)?'date':['weight','listedPrice','finalPrice','assessmentScore'].includes(k)?'number':'text'} value={draft[k]??''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <label>모프 기준 키<input className="input" list="cv-market-morphs" value={draft.morph} onChange={e=>setDraft({...draft,morph:e.target.value})}/><datalist id="cv-market-morphs">{Object.entries(PROFILES).map(([k,p])=><option key={k} value={k}>{p.label}</option>)}</datalist><small>복합은 lilly+axanthic처럼 +로 연결합니다.</small></label>
 {Object.entries({geneticsVerification:[['unknown','유전 미확인'],['verified','혈통·검사로 확인']],sex:[['unknown','미확정'],['male','수컷'],['female','암컷']],status:[['unsold','미판매'],['sold','판매 완료'],['cancelled','판매 취소'],['incomplete','기록 불완전']],verification:[['unverified','거래가 미검증'],['verified','최종 거래가 검증']],rights:[['unknown','권한 미확인'],['owned','본인 자료'],['permission','사용 허락 확보']]}).map(([k,opts])=><label key={k}>{({geneticsVerification:'유전 정보 검증',sex:'성별',status:'거래 상태',verification:'가격 검증',rights:'이용 권한'})[k]}<select className="input" value={draft[k]||'unknown'} onChange={e=>setDraft({...draft,[k]:e.target.value})}>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>)}
 </div><button className="btn btn-primary" onClick={()=>store([draft]).catch(e=>report(e.message))}>거래 저장</button>{errors.map((e,i)=><p role="alert" key={i}>{e.row}행: {e.message}</p>)}</div>
 <div className="card"><h2>CSV 가져오기</h2><button className="btn btn-secondary" onClick={()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob(['\uFEFF'+CSV_HEADER+'\n'],{type:'text/csv;charset=utf-8'}));a.href=u;a.download='crevalue-transactions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}>빈 CSV 템플릿 받기</button><label>CSV 파일<input className="input" type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files[0];if(f)setCsv(await f.text());}}/></label><label>CSV 내용<textarea className="input" rows="4" value={csv} onChange={e=>setCsv(e.target.value)}/></label><button className="btn btn-secondary" onClick={()=>{try{void store(parseCSV(csv),true).catch(e=>report(e.message));}catch(e){report(e.message);}}}>오류 검사 후 가져오기</button></div>
 <div className="card"><h2>저장된 거래 {rows.length}건</h2>{rows.map(r=><div className="cv-trait" key={r.id}><strong>{r.animalId||r.id.slice(0,8)} · {PROFILES[r.morph]?.label||r.morph}</strong><p>등록가 {r.listedPrice??'미입력'}원 / 거래가 {r.finalPrice??'미입력'}원 · {r.verification}</p><div className="cv-row"><button className="btn btn-secondary" onClick={()=>{setDraft(r);setEditing(r.id);}}>수정</button><button className="btn btn-secondary" onClick={async()=>{if(!confirm('이 거래를 가격 계산에서 제외하고 삭제 표시하시겠습니까?'))return;await bridge.remove('crevalue_market',r);await reload();}}>삭제</button></div></div>)}</div></>;
}

function Comparison({jobs,bridge,report}){
 const done=jobs.filter(j=>j.result),[left,setLeft]=useState(done[0]?.id||''),[right,setRight]=useState(done[1]?.id||''),[shownPair,setShownPair]=useState(''),[revealed,setRevealed]=useState(false),[feedback,setFeedback]=useState([]),[feedbackLoaded,setFeedbackLoaded]=useState(false),[reviewer,setReviewer]=useState('대표님'),[votes,setVotes]=useState({});
 useEffect(()=>{bridge.list('crevalue_feedback').then(rows=>{setFeedback(rows);setFeedbackLoaded(true);}).catch(e=>report(e.message));},[]);const stats=summarizeFeedback(feedback,jobs);
 const show=shownPair===left+'|'+right;
 const a=done.find(j=>j.id===left),b=done.find(j=>j.id===right);const comp=a&&b?compareAssessments(a.result,b.result):null;
 const [photos,setPhotos]=useState({}),[loadedPair,setLoadedPair]=useState('');
 useEffect(()=>{let active=true;setShownPair('');setRevealed(false);setVotes({});setPhotos({});setLoadedPair('');const pair=left+'|'+right;Promise.all([left,right].filter(Boolean).map(id=>bridge.get('crevalue',id))).then(records=>{if(!active)return;if(records.length!==2||records.some(r=>!r?.photos?.length))throw new Error('비교 사진을 불러오지 못했습니다.');setPhotos(Object.fromEntries(records.map(r=>[r.id,r.photos])));setLoadedPair(pair);}).catch(e=>{if(active)report(e.message);});return()=>{active=false;};},[left,right]);
 const photosReady=loadedPair===left+'|'+right;
 return <div className="card"><h2>개체 비교 · 성장 비교</h2><p className="cv-muted">같은 개체의 서로 다른 날짜를 고르면 성장 기록을 비교할 수 있습니다. 먼저 사진만 보고 평가한 뒤 AI 결과를 열 수 있습니다.</p><div className="cv-row">{[['왼쪽',left,setLeft],['오른쪽',right,setRight]].map(([label,v,set])=><label key={label}>{label}<select className="input" value={v} onChange={e=>set(e.target.value)}><option value="">기록 선택</option>{done.map(j=><option key={j.id} value={j.id}>{j.name} · {date(j.createdAt)}</option>)}</select></label>)}</div>
 {left&&left===right?<p role="alert">서로 다른 평가 기록을 선택해 주세요.</p>:comp?<><div className="cv-row">{[left,right].map(id=><div className="cv-photos" key={id}>{(photos[id]||[]).map(p=><div className="cv-photo" key={p.id}><img src={p.dataUrl} alt="블라인드 비교 사진"/></div>)}</div>)}</div><label>평가자<select className="input" value={reviewer} onChange={e=>setReviewer(e.target.value)}><option>대표님</option><option>공동 평가자</option></select></label>
 {comp.rows.map(r=><label key={r.id}>{r.label}<select className="input" value={votes[r.id]||'unknown'} onChange={e=>setVotes({...votes,[r.id]:e.target.value})}><option value="unknown">판단 보류</option><option value="a">왼쪽</option><option value="b">오른쪽</option><option value="tie">비슷함</option></select></label>)}
 <div className="cv-row"><button className="btn btn-secondary" disabled={!feedbackLoaded||!photosReady} onClick={async()=>{try{const latest=await bridge.list('crevalue_feedback');await bridge.save('crevalue_feedback',{id:uid(),left,right,reviewer,votes,blind:!revealed&&!wasSeen(left)&&!wasSeen(right)&&!latest.some(f=>f.type==='exposure'&&[left,right].includes(f.assessmentId)),createdAt:new Date().toISOString(),version:VERSION});setFeedback(await bridge.list('crevalue_feedback'));report('브리더 평가를 저장했습니다. 자동 정답으로 취급하지 않습니다.');await Promise.all([left,right].map(id=>markViewed(id,bridge)));setShownPair(left+'|'+right);setRevealed(true);}catch(e){report(e.message);}}}>브리더 평가 저장·결과 보기</button><button className="btn btn-secondary" disabled={!photosReady} onClick={async()=>{if(show){setShownPair('');return;}try{await Promise.all([left,right].map(id=>markViewed(id,bridge)));setShownPair(left+'|'+right);setRevealed(true);}catch(e){report(e.message);}}}>{show?'평가 결과 접기':'평가 결과 먼저 보기'}</button></div>
 {show&&<><p className="cv-notice">{comp.notice}</p>{comp.sameProfile&&<p>왼쪽 {a.result.score??'보류'}점 / 오른쪽 {b.result.score??'보류'}점</p>}<table className="cv-table"><thead><tr><th>항목</th><th>왼쪽</th><th>오른쪽</th><th>비교</th></tr></thead><tbody>{comp.rows.map(r=><tr key={r.id}><td>{r.label}</td><td>{r.a??'불가'}</td><td>{r.b??'불가'}</td><td>{r.judgement}</td></tr>)}</tbody></table></>}
 </>:<p className="cv-empty">평가 기록이 두 개 이상 필요합니다.</p>}
 <h3>누적 브리더 검증</h3><p className="cv-muted">같은 모프·버전의 AI 평가를 비교한 블라인드 기록 {stats.pairs}건입니다. 일치율은 참여자의 의견과의 일치이며 정확도나 정답률이 아닙니다.</p>{stats.traits.map(t=><details className="cv-trait" key={t.id}><summary>{t.label} · {t.matched}/{t.compared} 일치 ({t.rate}%)</summary>{t.disagreements.map((d,i)=><p key={i}>{d.reviewer} · 사람 {d.human==='a'?'왼쪽':d.human==='b'?'오른쪽':'비슷함'} / AI {d.ai==='a'?'왼쪽':d.ai==='b'?'오른쪽':'비슷함'}</p>)}</details>)}
 </div>;
}

function Screen({bridge,navigate,gecko}){
 installStyle();const [tab,setTab]=useState('analyze'),[animals]=useState(()=>bridge.animals()),[animalId,setAnimal]=useState(gecko?.id||''),[name,setName]=useState(gecko?.name||''),[morphs,setMorphs]=useState(morphKeys(gecko?.morph)),[photos,setPhotos]=useState([]),[jobs,setJobs]=useState([]),[selected,setSelected]=useState(null),[status,setStatus]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[forceReanalysis,setForceReanalysis]=useState(false),[photoUrl,setPhotoUrl]=useState(''),[blindMode,setBlindMode]=useState(false);
 const profile=profileFor(morphs.length?morphs:['normal']);
 const [client]=useState(()=>createWorkerClient(bridge));const worker=client.request;
 async function reload(){if(!bridge.isOwner())return;const rows=await bridge.list('crevalue',true);setJobs(rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))));try{const live=await worker('status');setStatus(live);setConnected(true);}catch{setConnected(false);}}
 async function connect(openWindow=false){setMessage('PC·Codex 연결을 확인하고 있습니다.');try{if(openWindow)await client.open();const s=await worker('status');setStatus(s);setConnected(true);setMessage(s.cloudError||s.quota.message);await reload();}catch(e){setConnected(false);setMessage('PC 분석 프로그램에 연결되지 않았습니다. 크레밸류 실행 후 위의 PC 연결 버튼을 눌러 주세요. 사진 요청은 서버에 대기시킬 수 있습니다. '+e.message);}}
 useEffect(()=>{void reload().catch(e=>setMessage(e.message));const t=setInterval(()=>void reload().catch(()=>{}),6000);return()=>{clearInterval(t);client.dispose();};},[]);
 async function pick(files){setBusy(true);try{if(photos.length+files.length>6)throw new Error('사진은 최대 6장입니다.');const next=await Promise.all(Array.from(files).map(resizePhoto));setPhotos(old=>old.concat(next));setSelected(null);setMessage('사진을 준비했습니다. 모프를 확인하고 분석해 주세요.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function submit(manual){setBusy(true);try{
  if(!photos.length)throw new Error('사진을 먼저 추가해 주세요.');if(!morphs.length)throw new Error('모프 기준을 선택해 주세요.');
  if(!manual&&connected){const s=await worker('status');setStatus(s);if(!s.quota.allowed)throw new Error(s.quota.message);}
  const job={id:uid(),animalId,animalSnapshot:animals.find(a=>a.id===animalId)||null,forceReanalysis,blindMode,name:name.trim()||'이름 없는 개체',morphs,photos,createdAt:new Date().toISOString(),status:manual?'completed':'queued',version:VERSION,...(manual?{result:manual}:{}),rights:{analysisAllowed:true,trainingAllowed:false}};
  await bridge.save('crevalue',job);setSelected(job.id);setJobs(old=>[job,...old]);
  if(!manual){try{await worker('jobs',job);setConnected(true);setMessage('분석을 접수했습니다. 결과가 자동으로 표시됩니다.');}catch{setConnected(false);setMessage('사진을 서버에 저장했습니다. PC 분석 프로그램이 연결되면 처리합니다.');}}
  else setMessage('수동 평가를 저장했습니다.');await reload();
 }catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const current=jobs.find(j=>j.id===selected);
 if(!bridge.isOwner())return <div className="screen cv"><div className="cv-main"><p>대표님 전용 기능입니다.</p><button className="btn btn-secondary" onClick={()=>navigate('home')}>홈으로</button></div></div>;
 return <div className="screen cv"><div className="header"><div className="header-row"><button className="back-btn" onClick={()=>navigate('home')}>‹ 브리딩비서</button><h1 style={{fontSize:17}}>크레밸류</h1></div></div><main className="cv-main">
 <div className="card cv-hero"><small>CREVALUE · 대표님 전용 시험판</small><h2 style={{marginTop:8}}>사진으로 살펴보는 우리 개체의 특징</h2><div className="cv-muted">{connected?'PC 연결됨':'PC 연결 대기'} · {status?.quota?.remaining!=null?`구독 잔여 ${status.quota.remaining}%`:'구독 한도 확인 필요'} · 10% 보호</div><button className="btn btn-secondary" style={{marginTop:10}} onClick={()=>connect(true)}>PC 연결·사용 한도 확인</button><p className="cv-muted">PC 연결 창이 열리면 그대로 두고 이 화면에서 평가해 주세요.</p></div>
 <nav className="cv-nav" aria-label="크레밸류 메뉴">{[['analyze','사진 평가'],['history','평가 기록'],['compare','비교·성장'],['market','거래·가격'],['criteria','평가 기준']].map(([k,l])=><button className={'chip-btn '+(tab===k?'active':'')} aria-pressed={tab===k} key={k} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {message&&<p className="cv-notice" role="status" aria-atomic="true">{message}</p>}
 {tab==='analyze'&&<><section className="card"><h2>1. 개체와 사진</h2><label>등록된 개체<select className="input" value={animalId} disabled={busy} onChange={e=>{setPhotos([]);setSelected(null);setMessage('개체를 바꾸어 사진 선택을 초기화했습니다.');const a=animals.find(x=>x.id===e.target.value);setAnimal(a?.id||'');setName(a?.name||'');if(a?.morph)setMorphs(morphKeys(a.morph));}}><option value="">사진만으로 새 평가</option>{animals.map(a=><option value={a.id} key={a.id}>{a.name} · {a.morph||'모프 미입력'}</option>)}</select></label><label>평가 이름<input className="input" value={name} maxLength="100" onChange={e=>setName(e.target.value)} placeholder="개체 이름 또는 구분할 이름"/></label>
 <label>사진 추가 · 최대 6장<input className="input" type="file" accept="image/*" multiple disabled={busy} onChange={e=>{void pick(e.target.files);e.target.value='';}}/></label>
 <details><summary style={{cursor:'pointer',padding:'8px 0'}}>웹에 저장한 사진 주소로 추가</summary><label>사진 주소<input className="input" type="url" value={photoUrl} onChange={e=>setPhotoUrl(e.target.value)} placeholder="https://…"/></label><button className="btn btn-secondary" disabled={busy||!photoUrl} onClick={async()=>{setBusy(true);try{if(photos.length>=6)throw new Error('사진은 최대 6장입니다.');const u=new URL(photoUrl);if(u.protocol!=='https:'||u.username||u.password)throw new Error('인증 정보가 없는 HTTPS 사진 주소를 입력해 주세요.');const response=await fetch(u.href,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('사진 주소에 접근할 수 없습니다.');const photo=await resizePhoto(await response.blob());setPhotos(old=>old.concat(photo));setSelected(null);setPhotoUrl('');setMessage('사진을 추가했습니다. 모프를 확인하고 분석해 주세요.');}catch(e){setMessage('사진을 가져오지 못했습니다. 직접 파일을 선택하시거나 주소를 확인해 주세요. '+e.message);}finally{setBusy(false);}}}>주소의 사진 불러오기</button><p className="cv-muted">본인 사진 또는 사용 허락이 있는 사진만 추가하십시오. 사이트가 외부 읽기를 허용하지 않으면 파일로 선택해 주세요.</p></details>
 {animalId&&<button className="btn btn-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const urls=bridge.photos(animalId).slice(0,6-photos.length);if(!urls.length)throw new Error('불러올 사진이 없습니다. 사진 추가로 선택해 주세요.');const result=[];for(const url of urls){const response=await fetch(url);if(!response.ok)throw new Error('기존 사진을 읽지 못했습니다.');result.push(await resizePhoto(await response.blob()));}setPhotos(old=>old.concat(result));}catch(e){setMessage(e.message);}finally{setBusy(false);}}}>기존 개체 사진 불러오기</button>}
 <p className="cv-muted">등·좌측·우측·얼굴 사진을 권장합니다. 한 장으로도 보이는 항목부터 평가합니다. 사진은 ChatGPT 구독으로 전송하여 분석합니다. 크레밸류 학습자료 제공에는 사용하지 않으며, 외부 AI의 데이터 처리는 ChatGPT 계정 설정이 적용됩니다.</p>
 <div className="cv-photos">{photos.map((p,i)=><div className="cv-photo" key={p.id}><img src={p.dataUrl} alt={`분석 사진 ${i+1}`}/><label>사진 {i+1} 각도<select value={p.angle} onChange={e=>setPhotos(photos.map(x=>x.id===p.id?{...x,angle:e.target.value}:x))}>{['미지정','등','좌측','우측','얼굴','전신'].map(v=><option key={v}>{v}</option>)}</select></label><label>발색 상태<select value={p.fired} onChange={e=>setPhotos(photos.map(x=>x.id===p.id?{...x,fired:e.target.value}:x))}>{['미확인','파이어업','파이어다운'].map(v=><option key={v}>{v}</option>)}</select></label><button className="btn btn-secondary" onClick={()=>setPhotos(photos.filter(x=>x.id!==p.id))}>사진 {i+1} 제외</button></div>)}</div></section>
 <section className="card"><h2>2. 평가 기준</h2><p className="cv-muted">복합 모프는 여러 개 선택하십시오. 모프 미확정은 노멀의 공통 외형 기준으로 관찰하며 유전자형을 확정하지 않습니다.</p><div className="cv-morphs">{Object.entries(PROFILES).map(([id,p])=><button key={id} aria-pressed={morphs.includes(id)} onClick={()=>setMorphs(morphs.includes(id)?morphs.filter(x=>x!==id):[...morphs,id])}>{p.label}</button>)}</div><button className="btn btn-primary" disabled={busy||!photos.length||!morphs.length} onClick={()=>submit()}>{busy?'사진 준비·저장 중…':'사진 분석하기'}</button><label style={{marginTop:12}}><input type="checkbox" checked={blindMode} onChange={e=>setBlindMode(e.target.checked)}/> 블라인드 비교용으로 결과를 가리고 저장</label><label style={{marginTop:12}}><input type="checkbox" checked={forceReanalysis} onChange={e=>setForceReanalysis(e.target.checked)}/> 기존 결과를 재사용하지 않고 다시 관찰하기 (재현성 검증용)</label><Manual profile={profile} photos={photos} onSave={submit}/></section>
 {current&&<section className="card"><h2>3. {statuses[current.status]||'평가 결과'}</h2><>{current.blindMode&&current.result&&!wasSeen(current.id)?<p>블라인드 비교용으로 저장했습니다. 비교·성장에서 사진을 먼저 평가해 주세요.</p>:<Result job={{...current,photos}} bridge={bridge}/>}</>{['error','blocked'].includes(current.status)&&<button className="btn btn-secondary" onClick={async()=>{try{await worker('retry',{id:current.id});setMessage('분석을 다시 요청했습니다.');await reload();}catch(e){setMessage(e.message);}}}>다시 분석</button>}</section>}</>}
 {tab==='history'&&<div className="card"><h2>평가 기록</h2><button className="btn btn-secondary" onClick={async()=>{try{exportJson(await bridge.list('crevalue'),'crevalue-assessments-with-photos.json');}catch(e){setMessage(e.message);}}}>평가 결과 내보내기</button>{!jobs.length&&<p className="cv-empty">아직 평가 기록이 없습니다. 사진 평가에서 시작해 주세요.</p>}{jobs.map(j=><HistoryRecord key={j.id} job={j} bridge={bridge} report={setMessage} onRetry={id=>worker('retry',{id}).then(reload).catch(e=>setMessage(e.message))}/>)}</div>}
 {tab==='compare'&&<Comparison jobs={jobs} bridge={bridge} report={setMessage}/>}
 {tab==='market'&&<Market bridge={bridge} animals={animals} report={setMessage}/>}
 {tab==='criteria'&&<div className="card"><h2>검토 전 평가 기준</h2><p className="cv-notice">모든 점수와 가중치는 CREVALUE의 임시 가설입니다. 브리더 검증·시장 표준·건강 검사 결과가 아닙니다.</p><p>같은 사진·같은 모프·같은 기준 버전의 완료된 AI 평가는 재사용하여 불필요한 호출과 점수 변동을 줄입니다. 관찰 범위가 45% 미만이거나 항목이 두 개 미만이면 종합 점수를 보류합니다.</p>{Object.entries(PROFILES).map(([id,p])=><details key={id} className="cv-trait"><summary>{p.label}</summary>{Object.entries(p.weights).map(([k,w])=><p key={k}>{TRAITS[k][0]} {w}% · {TRAITS[k][1]}</p>)}</details>)}<h3>기준 자료</h3>{SOURCES.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><br/>{s.note}</p>)}<p className="cv-muted">{VERSION} · 노멀·릴리화이트·아잔틱 우선 검증. 초초·하이포 등 명칭과 기준은 대표님 검토 전입니다. 실거래 자료를 외형 점수에 섞지 않습니다.</p></div>}
 </main></div>;
}
window.CREG_VALUE={Screen};
